# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscribe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='subscribe.proto',
  package='mateROV',
  syntax='proto2',
  serialized_pb=_b('\n\x0fsubscribe.proto\x12\x07mateROV\"\x1e\n\tSubscribe\x12\x11\n\tmsg_types\x18\x01 \x03(\x05')
)




_SUBSCRIBE = _descriptor.Descriptor(
  name='Subscribe',
  full_name='mateROV.Subscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_types', full_name='mateROV.Subscribe.msg_types', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['Subscribe'] = _SUBSCRIBE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subscribe = _reflection.GeneratedProtocolMessageType('Subscribe', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBE,
  __module__ = 'subscribe_pb2'
  # @@protoc_insertion_point(class_scope:mateROV.Subscribe)
  ))
_sym_db.RegisterMessage(Subscribe)


# @@protoc_insertion_point(module_scope)
