# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cameraFrameMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cameraFrameMsg.proto',
  package='mateROV',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x63\x61meraFrameMsg.proto\x12\x07mateROV\"1\n\x0e\x43\x61meraFrameMsg\x12\x13\n\x0b\x63\x61meraFrame\x18\x01 \x02(\x0c\x12\n\n\x02id\x18\x02 \x02(\x05')
)




_CAMERAFRAMEMSG = _descriptor.Descriptor(
  name='CameraFrameMsg',
  full_name='mateROV.CameraFrameMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameraFrame', full_name='mateROV.CameraFrameMsg.cameraFrame', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='mateROV.CameraFrameMsg.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['CameraFrameMsg'] = _CAMERAFRAMEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraFrameMsg = _reflection.GeneratedProtocolMessageType('CameraFrameMsg', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAFRAMEMSG,
  __module__ = 'cameraFrameMsg_pb2'
  # @@protoc_insertion_point(class_scope:mateROV.CameraFrameMsg)
  ))
_sym_db.RegisterMessage(CameraFrameMsg)


# @@protoc_insertion_point(module_scope)
