# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: humidityMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='humidityMsg.proto',
  package='mateROV',
  syntax='proto2',
  serialized_pb=_b('\n\x11humidityMsg.proto\x12\x07mateROV\"\x1f\n\x0bHumidityMsg\x12\x10\n\x08humidity\x18\x01 \x02(\x02')
)




_HUMIDITYMSG = _descriptor.Descriptor(
  name='HumidityMsg',
  full_name='mateROV.HumidityMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='humidity', full_name='mateROV.HumidityMsg.humidity', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['HumidityMsg'] = _HUMIDITYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HumidityMsg = _reflection.GeneratedProtocolMessageType('HumidityMsg', (_message.Message,), dict(
  DESCRIPTOR = _HUMIDITYMSG,
  __module__ = 'humidityMsg_pb2'
  # @@protoc_insertion_point(class_scope:mateROV.HumidityMsg)
  ))
_sym_db.RegisterMessage(HumidityMsg)


# @@protoc_insertion_point(module_scope)
