protobuf: mockMsg.proto cameraFrameMsg.proto ctrlMsg.proto humidityMsg.proto orientationMsg.proto
	protoc -I=./ --python_out=./ ./mockMsg.proto
	protoc -I=./ --python_out=./ ./cameraFrameMsg.proto
	protoc -I=./ --python_out=./ ./ctrlMsg.proto
	protoc -I=./ --python_out=./ ./humidityMsg.proto
	protoc -I=./ --python_out=./ ./orientationMsg.proto
