protobuf: mockMsg.proto cameraFrameMsg.proto ctrlMsg.proto
	protoc -I=./ --python_out=./ ./mockMsg.proto
	protoc -I=./ --python_out=./ ./cameraFrameMsg.proto
	protoc -I=./ --python_out=./ ./ctrlMsg.proto
