# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orientationMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orientationMsg.proto',
  package='mateROV',
  syntax='proto2',
  serialized_pb=_b('\n\x14orientationMsg.proto\x12\x07mateROV\":\n\x0eOrientationMsg\x12\x0c\n\x04roll\x18\x01 \x02(\x02\x12\r\n\x05pitch\x18\x02 \x02(\x02\x12\x0b\n\x03yaw\x18\x03 \x02(\x02')
)




_ORIENTATIONMSG = _descriptor.Descriptor(
  name='OrientationMsg',
  full_name='mateROV.OrientationMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='mateROV.OrientationMsg.roll', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='mateROV.OrientationMsg.pitch', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='mateROV.OrientationMsg.yaw', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['OrientationMsg'] = _ORIENTATIONMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrientationMsg = _reflection.GeneratedProtocolMessageType('OrientationMsg', (_message.Message,), dict(
  DESCRIPTOR = _ORIENTATIONMSG,
  __module__ = 'orientationMsg_pb2'
  # @@protoc_insertion_point(class_scope:mateROV.OrientationMsg)
  ))
_sym_db.RegisterMessage(OrientationMsg)


# @@protoc_insertion_point(module_scope)
